// <auto-generated />
using System;
using DEPI_Library.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DEPI_Library.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20250501181516_FixedDB")]
    partial class FixedDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DEPI_Library.Models.Admin", b =>
                {
                    b.Property<long>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdminId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1L,
                            Email = "alice@admin.com",
                            Name = "Alice Admin",
                            Password = "admin123"
                        },
                        new
                        {
                            AdminId = 2L,
                            Email = "bob@admin.com",
                            Name = "Bob Admin",
                            Password = "admin123"
                        });
                });

            modelBuilder.Entity("DEPI_Library.Models.Book", b =>
                {
                    b.Property<long>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BookId"));

                    b.Property<long?>("AdminId")
                        .HasColumnType("bigint");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("AdminId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1L,
                            AdminId = 1L,
                            Author = "Frank Herbert",
                            CategoryId = 1L,
                            Description = "A desert planet and political intrigue.",
                            Title = "Dune"
                        },
                        new
                        {
                            BookId = 2L,
                            AdminId = 1L,
                            Author = "William Gibson",
                            CategoryId = 1L,
                            Description = "Cyberpunk pioneer.",
                            Title = "Neuromancer"
                        },
                        new
                        {
                            BookId = 3L,
                            AdminId = 1L,
                            Author = "Isaac Asimov",
                            CategoryId = 1L,
                            Description = "A galactic empire's fall.",
                            Title = "Foundation"
                        },
                        new
                        {
                            BookId = 4L,
                            AdminId = 1L,
                            Author = "Neal Stephenson",
                            CategoryId = 1L,
                            Description = "A hacker in the Metaverse.",
                            Title = "Snow Crash"
                        },
                        new
                        {
                            BookId = 5L,
                            AdminId = 2L,
                            Author = "Dan Simmons",
                            CategoryId = 1L,
                            Description = "Pilgrims on a doomed world.",
                            Title = "Hyperion"
                        },
                        new
                        {
                            BookId = 6L,
                            AdminId = 2L,
                            Author = "Ursula K. Le Guin",
                            CategoryId = 1L,
                            Description = "Gender and diplomacy on another planet.",
                            Title = "The Left Hand of Darkness"
                        },
                        new
                        {
                            BookId = 7L,
                            AdminId = 2L,
                            Author = "Andy Weir",
                            CategoryId = 1L,
                            Description = "Survival on Mars.",
                            Title = "The Martian"
                        },
                        new
                        {
                            BookId = 8L,
                            AdminId = 2L,
                            Author = "Kim Stanley Robinson",
                            CategoryId = 1L,
                            Description = "Terraforming Mars.",
                            Title = "Red Mars"
                        },
                        new
                        {
                            BookId = 9L,
                            AdminId = 1L,
                            Author = "Peter Watts",
                            CategoryId = 1L,
                            Description = "Contact with alien intelligence.",
                            Title = "Blindsight"
                        },
                        new
                        {
                            BookId = 10L,
                            AdminId = 1L,
                            Author = "Robert A. Heinlein",
                            CategoryId = 1L,
                            Description = "Military science fiction.",
                            Title = "Starship Troopers"
                        },
                        new
                        {
                            BookId = 11L,
                            AdminId = 1L,
                            Author = "Yuval Noah Harari",
                            CategoryId = 2L,
                            Description = "Human evolution and culture.",
                            Title = "Sapiens"
                        },
                        new
                        {
                            BookId = 12L,
                            AdminId = 1L,
                            Author = "Jared Diamond",
                            CategoryId = 2L,
                            Description = "Geography and societal development.",
                            Title = "Guns, Germs, and Steel"
                        },
                        new
                        {
                            BookId = 13L,
                            AdminId = 2L,
                            Author = "Peter Frankopan",
                            CategoryId = 2L,
                            Description = "History through trade routes.",
                            Title = "The Silk Roads"
                        },
                        new
                        {
                            BookId = 14L,
                            AdminId = 2L,
                            Author = "Susan Wise Bauer",
                            CategoryId = 2L,
                            Description = "From the earliest accounts.",
                            Title = "The History of the Ancient World"
                        },
                        new
                        {
                            BookId = 15L,
                            AdminId = 1L,
                            Author = "David McCullough",
                            CategoryId = 2L,
                            Description = "American Revolution.",
                            Title = "1776"
                        },
                        new
                        {
                            BookId = 16L,
                            AdminId = 2L,
                            Author = "Thomas Asbridge",
                            CategoryId = 2L,
                            Description = "Religious wars of Europe.",
                            Title = "The Crusades"
                        },
                        new
                        {
                            BookId = 17L,
                            AdminId = 1L,
                            Author = "Tony Judt",
                            CategoryId = 2L,
                            Description = "Europe after WWII.",
                            Title = "Postwar"
                        },
                        new
                        {
                            BookId = 18L,
                            AdminId = 2L,
                            Author = "John Lewis Gaddis",
                            CategoryId = 2L,
                            Description = "Superpower tension.",
                            Title = "The Cold War"
                        },
                        new
                        {
                            BookId = 19L,
                            AdminId = 1L,
                            Author = "Howard Zinn",
                            CategoryId = 2L,
                            Description = "History from below.",
                            Title = "A People's History of the United States"
                        },
                        new
                        {
                            BookId = 20L,
                            AdminId = 1L,
                            Author = "David McCullough",
                            CategoryId = 2L,
                            Description = "Early aviation.",
                            Title = "The Wright Brothers"
                        },
                        new
                        {
                            BookId = 21L,
                            AdminId = 2L,
                            Author = "Robert C. Martin",
                            CategoryId = 3L,
                            Description = "Write readable code.",
                            Title = "Clean Code"
                        },
                        new
                        {
                            BookId = 22L,
                            AdminId = 2L,
                            Author = "Andy Hunt",
                            CategoryId = 3L,
                            Description = "Programming philosophy.",
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            BookId = 23L,
                            AdminId = 2L,
                            Author = "Erich Gamma et al.",
                            CategoryId = 3L,
                            Description = "Reusable object-oriented solutions.",
                            Title = "Design Patterns"
                        },
                        new
                        {
                            BookId = 24L,
                            AdminId = 2L,
                            Author = "Martin Fowler",
                            CategoryId = 3L,
                            Description = "Improve existing code.",
                            Title = "Refactoring"
                        },
                        new
                        {
                            BookId = 25L,
                            AdminId = 2L,
                            Author = "Eric Evans",
                            CategoryId = 3L,
                            Description = "Complex software design.",
                            Title = "Domain-Driven Design"
                        },
                        new
                        {
                            BookId = 26L,
                            AdminId = 1L,
                            Author = "Kyle Simpson",
                            CategoryId = 3L,
                            Description = "Deep JavaScript concepts.",
                            Title = "You Don’t Know JS"
                        },
                        new
                        {
                            BookId = 27L,
                            AdminId = 1L,
                            Author = "Jon Skeet",
                            CategoryId = 3L,
                            Description = "Advanced C# concepts.",
                            Title = "C# in Depth"
                        },
                        new
                        {
                            BookId = 28L,
                            AdminId = 1L,
                            Author = "Steve McConnell",
                            CategoryId = 3L,
                            Description = "Software construction.",
                            Title = "Code Complete"
                        },
                        new
                        {
                            BookId = 29L,
                            AdminId = 1L,
                            Author = "Frederick Brooks",
                            CategoryId = 3L,
                            Description = "Software project management.",
                            Title = "The Mythical Man-Month"
                        },
                        new
                        {
                            BookId = 30L,
                            AdminId = 2L,
                            Author = "Gayle Laakmann McDowell",
                            CategoryId = 3L,
                            Description = "Interview preparation.",
                            Title = "Cracking the Coding Interview"
                        },
                        new
                        {
                            BookId = 31L,
                            AdminId = 1L,
                            Author = "J.R.R. Tolkien",
                            CategoryId = 4L,
                            Description = "A journey to the Lonely Mountain.",
                            Title = "The Hobbit"
                        },
                        new
                        {
                            BookId = 32L,
                            AdminId = 1L,
                            Author = "J.R.R. Tolkien",
                            CategoryId = 4L,
                            Description = "First part of Lord of the Rings.",
                            Title = "The Fellowship of the Ring"
                        },
                        new
                        {
                            BookId = 33L,
                            AdminId = 2L,
                            Author = "George R. R. Martin",
                            CategoryId = 4L,
                            Description = "War of the Seven Kingdoms.",
                            Title = "A Game of Thrones"
                        },
                        new
                        {
                            BookId = 34L,
                            AdminId = 2L,
                            Author = "Patrick Rothfuss",
                            CategoryId = 4L,
                            Description = "A wizard’s coming of age.",
                            Title = "The Name of the Wind"
                        },
                        new
                        {
                            BookId = 35L,
                            AdminId = 2L,
                            Author = "Brandon Sanderson",
                            CategoryId = 4L,
                            Description = "Epic fantasy world.",
                            Title = "The Way of Kings"
                        },
                        new
                        {
                            BookId = 36L,
                            AdminId = 2L,
                            Author = "Brandon Sanderson",
                            CategoryId = 4L,
                            Description = "Magical heists.",
                            Title = "Mistborn"
                        },
                        new
                        {
                            BookId = 37L,
                            AdminId = 1L,
                            Author = "Christopher Paolini",
                            CategoryId = 4L,
                            Description = "A dragon rider's tale.",
                            Title = "Eragon"
                        },
                        new
                        {
                            BookId = 38L,
                            AdminId = 1L,
                            Author = "Robert Jordan",
                            CategoryId = 4L,
                            Description = "A long prophecy-filled saga.",
                            Title = "The Wheel of Time"
                        },
                        new
                        {
                            BookId = 39L,
                            AdminId = 1L,
                            Author = "C.S. Lewis",
                            CategoryId = 4L,
                            Description = "Fantasy for all ages.",
                            Title = "The Chronicles of Narnia"
                        },
                        new
                        {
                            BookId = 40L,
                            AdminId = 1L,
                            Author = "Scott Lynch",
                            CategoryId = 4L,
                            Description = "Fantasy thievery.",
                            Title = "The Lies of Locke Lamora"
                        },
                        new
                        {
                            BookId = 41L,
                            AdminId = 2L,
                            Author = "Anne Frank",
                            CategoryId = 5L,
                            Description = "A teenage girl's WWII diary.",
                            Title = "The Diary of Anne Frank"
                        },
                        new
                        {
                            BookId = 42L,
                            AdminId = 2L,
                            Author = "Nelson Mandela",
                            CategoryId = 5L,
                            Description = "Mandela's autobiography.",
                            Title = "Long Walk to Freedom"
                        },
                        new
                        {
                            BookId = 43L,
                            AdminId = 1L,
                            Author = "Walter Isaacson",
                            CategoryId = 5L,
                            Description = "Biography of Apple founder.",
                            Title = "Steve Jobs"
                        },
                        new
                        {
                            BookId = 44L,
                            AdminId = 1L,
                            Author = "Walter Isaacson",
                            CategoryId = 5L,
                            Description = "Biography of Albert Einstein.",
                            Title = "Einstein"
                        },
                        new
                        {
                            BookId = 45L,
                            AdminId = 2L,
                            Author = "Michelle Obama",
                            CategoryId = 5L,
                            Description = "Memoir of the First Lady.",
                            Title = "Becoming"
                        },
                        new
                        {
                            BookId = 46L,
                            AdminId = 2L,
                            Author = "Tara Westover",
                            CategoryId = 5L,
                            Description = "A woman’s quest for knowledge.",
                            Title = "Educated"
                        },
                        new
                        {
                            BookId = 47L,
                            AdminId = 1L,
                            Author = "Paul Kalanithi",
                            CategoryId = 5L,
                            Description = "Life and death of a doctor.",
                            Title = "When Breath Becomes Air"
                        },
                        new
                        {
                            BookId = 48L,
                            AdminId = 1L,
                            Author = "David McCullough",
                            CategoryId = 5L,
                            Description = "Pioneers of aviation.",
                            Title = "The Wright Brothers"
                        },
                        new
                        {
                            BookId = 49L,
                            AdminId = 1L,
                            Author = "Walter Isaacson",
                            CategoryId = 5L,
                            Description = "Renaissance genius.",
                            Title = "Leonardo da Vinci"
                        },
                        new
                        {
                            BookId = 50L,
                            AdminId = 2L,
                            Author = "Tina Fey",
                            CategoryId = 5L,
                            Description = "Comedian’s life story.",
                            Title = "Bossypants"
                        },
                        new
                        {
                            BookId = 51L,
                            AdminId = 2L,
                            Author = "Plato",
                            CategoryId = 6L,
                            Description = "Justice and politics.",
                            Title = "The Republic"
                        },
                        new
                        {
                            BookId = 52L,
                            AdminId = 1L,
                            Author = "Marcus Aurelius",
                            CategoryId = 6L,
                            Description = "Stoic thoughts of a Roman emperor.",
                            Title = "Meditations"
                        },
                        new
                        {
                            BookId = 53L,
                            AdminId = 2L,
                            Author = "Friedrich Nietzsche",
                            CategoryId = 6L,
                            Description = "Moral philosophy.",
                            Title = "Beyond Good and Evil"
                        },
                        new
                        {
                            BookId = 54L,
                            AdminId = 2L,
                            Author = "Immanuel Kant",
                            CategoryId = 6L,
                            Description = "Theory of knowledge.",
                            Title = "Critique of Pure Reason"
                        },
                        new
                        {
                            BookId = 55L,
                            AdminId = 2L,
                            Author = "Martin Heidegger",
                            CategoryId = 6L,
                            Description = "Existential ontology.",
                            Title = "Being and Time"
                        },
                        new
                        {
                            BookId = 56L,
                            AdminId = 1L,
                            Author = "Niccolò Machiavelli",
                            CategoryId = 6L,
                            Description = "Power and politics.",
                            Title = "The Prince"
                        },
                        new
                        {
                            BookId = 57L,
                            AdminId = 1L,
                            Author = "Laozi",
                            CategoryId = 6L,
                            Description = "Taoist philosophy.",
                            Title = "Tao Te Ching"
                        },
                        new
                        {
                            BookId = 58L,
                            AdminId = 1L,
                            Author = "Sun Tzu",
                            CategoryId = 6L,
                            Description = "Strategy and conflict.",
                            Title = "The Art of War"
                        },
                        new
                        {
                            BookId = 59L,
                            AdminId = 2L,
                            Author = "Seneca",
                            CategoryId = 6L,
                            Description = "Roman Stoic wisdom.",
                            Title = "Letters from a Stoic"
                        },
                        new
                        {
                            BookId = 60L,
                            AdminId = 2L,
                            Author = "Albert Camus",
                            CategoryId = 6L,
                            Description = "Absurdism and meaning.",
                            Title = "The Myth of Sisyphus"
                        });
                });

            modelBuilder.Entity("DEPI_Library.Models.Borrow", b =>
                {
                    b.Property<long>("BorrowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BorrowId"));

                    b.Property<long?>("BookId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("BorrowDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("BorrowId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Borrows");

                    b.HasData(
                        new
                        {
                            BorrowId = 1L,
                            BookId = 1L,
                            BorrowDate = new DateTimeOffset(new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = 1L
                        },
                        new
                        {
                            BorrowId = 2L,
                            BookId = 2L,
                            BorrowDate = new DateTimeOffset(new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = 1L
                        },
                        new
                        {
                            BorrowId = 3L,
                            BookId = 3L,
                            BorrowDate = new DateTimeOffset(new DateTime(2025, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = 2L
                        },
                        new
                        {
                            BorrowId = 4L,
                            BookId = 4L,
                            BorrowDate = new DateTimeOffset(new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = 2L
                        },
                        new
                        {
                            BorrowId = 5L,
                            BookId = 5L,
                            BorrowDate = new DateTimeOffset(new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("DEPI_Library.Models.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1L,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            CategoryId = 2L,
                            Name = "Fantasy"
                        },
                        new
                        {
                            CategoryId = 3L,
                            Name = "Mystery"
                        },
                        new
                        {
                            CategoryId = 4L,
                            Name = "Biography"
                        },
                        new
                        {
                            CategoryId = 5L,
                            Name = "History"
                        },
                        new
                        {
                            CategoryId = 6L,
                            Name = "Self Help"
                        });
                });

            modelBuilder.Entity("DEPI_Library.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            Email = "john@example.com",
                            Name = "John Doe",
                            Password = "user123",
                            Phone = "1234567890"
                        },
                        new
                        {
                            UserId = 2L,
                            Email = "jane@example.com",
                            Name = "Jane Smith",
                            Password = "user123",
                            Phone = "9876543210"
                        });
                });

            modelBuilder.Entity("DEPI_Library.Models.Book", b =>
                {
                    b.HasOne("DEPI_Library.Models.Admin", "Admin")
                        .WithMany("Books")
                        .HasForeignKey("AdminId");

                    b.HasOne("DEPI_Library.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Admin");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DEPI_Library.Models.Borrow", b =>
                {
                    b.HasOne("DEPI_Library.Models.Book", "Book")
                        .WithMany("Borrows")
                        .HasForeignKey("BookId");

                    b.HasOne("DEPI_Library.Models.User", "User")
                        .WithMany("Borrows")
                        .HasForeignKey("UserId");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DEPI_Library.Models.Admin", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DEPI_Library.Models.Book", b =>
                {
                    b.Navigation("Borrows");
                });

            modelBuilder.Entity("DEPI_Library.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DEPI_Library.Models.User", b =>
                {
                    b.Navigation("Borrows");
                });
#pragma warning restore 612, 618
        }
    }
}
